// sphere-loader.js — the YourMine sphere that runs a PUBLISHED Aiwa contract, and what goes with it.
//
// A sphere must not carry its own copy of a contract: the point of publishing it in Aiwa is that the
// published version is immutable. So the sphere generated here holds only the contract's IDENTITY — who
// published it, its address, and the id of its manifest event (the hash of that exact version) — and is
// pinned to it. At run time it fetches the signed events from wherever they are, checks every signature
// and every hash with aiwa-core's own verifyEvent, and only then runs the code. Same id, same bytes.
//
// Why verifyEvent event by event instead of appending to an EventLog: EventLog.append demands every parent
// of an event to be known, and a manifest's parents include the heads of the publisher's WHOLE log (their
// wallet history). verifyEvent needs none of that: the public key travels in the event, the id is the hash
// of its content, the signature is checked against the key. The manifest names each file event by its id,
// each file event's id is the hash of its content: pinning the manifest id pins every byte.
//
// Where the events come from, in this order: what this device already verified (kept by the hash);
// the public address of an export, if the sphere was given one; the Aiwa page of this device, in a window
// the user allows (bundle-provider.html — a cross-site iframe would only see a partitioned, empty storage).

const PAGE = 'https://theodoreyong9.github.io/Aiwa_project/';

/** text as the inside of a single-quoted JS literal YourMine's merge.js can read: 1 to 120 characters between apostrophes, no $ { } or line break. */
export function sanitizeMeta(text, limit = 120) {
  text = String(text ?? '').replace(/'/g, '\u2019').replace(/[\\$\{\}\u0000-\u001f]/g, ' ').replace(/ {2,}/g, ' ').trim();
  if (text.length <= limit) return text;
  const cut = text.slice(0, limit - 1);
  const words = cut.includes(' ', Math.floor(limit / 2)) ? cut.slice(0, cut.lastIndexOf(' ')) : cut;
  return words.replace(/[ ,;:-]+$/, '') + '\u2026';
}

/** The sphere's name, description and icon, read from the contract's own <title> and <meta> tags (needs a DOM). */
export function contractMeta(html, fallbackName) {
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const meta = (name) => doc.querySelector(`meta[name="${name}"]`)?.getAttribute('content')?.trim() || '';
  const title = sanitizeMeta(doc.querySelector('title')?.textContent || '', 120) || sanitizeMeta(fallbackName, 120);
  return {
    title,
    description: sanitizeMeta(meta('description') || `${title} — an Aiwa contract, run inside YourMine.`, 120),
    icon: sanitizeMeta(meta('aiwa-icon') || '\u{1F537}', 8) || '\u{1F537}',
  };
}

/** The signed events that ARE a published version — its manifest and its files, nothing else (no ancestors, no wallet history). Null when the log does not hold them. */
export async function exportPackage(log, manifestEventId) {
  const manifest = await log.get(manifestEventId);
  if (!manifest || manifest.type !== 'bundle.manifest') return null;
  const files = [];
  for (const id of Object.values(manifest.payload.files ?? {})) {
    const event = await log.get(id);
    if (!event || event.type !== 'bundle.file') return null;
    files.push(event);
  }
  return { manifest, files };
}

/** YourMine's address that opens Build → Apps with a sphere in the code field (the `#aiwa=1;name;code` hand-off of YourMine's build.js; code = deflate-raw, base64url). */
export async function yourMineUrl(fileName, source, base = 'https://yourmine-dapp.web.app/') {
  const packed = await new Response(new Blob([new TextEncoder().encode(source)]).stream().pipeThrough(new CompressionStream('deflate-raw'))).arrayBuffer();
  let binary = '';
  for (const byte of new Uint8Array(packed)) binary += String.fromCharCode(byte);
  const payload = btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  return `${base}#aiwa=1;${fileName};${payload}`;
}

const HEX = /^[0-9a-f]{64}$/;
const DOMAIN = /^contract:[0-9a-f]{64}:[A-Za-z0-9_.-]{1,80}$/;
const SLUG = /^[A-Za-z0-9][A-Za-z0-9_-]{0,40}$/;

// The sphere, as text. __X__ placeholders are replaced in buildSphere (the values are validated there).
const TEMPLATE = String.raw`/* jshint esversion:11 */
// Generated by the Aiwa wallet page (github.com/theodoreyong9/Aiwa_project) for the contract __DOMAIN__.
// This sphere holds NO copy of the contract: it is pinned to the published version by the id of its
// manifest, fetches the signed events, checks every signature and hash, and only then runs the code.
(function(){
'use strict';
window.YM_S = window.YM_S || {};
const PIN = { author: '__AUTHOR__', domain: '__DOMAIN__', manifest: '__MANIFEST__' };
const BASE = '__SLUG__';
const EVENTS_URL = __EVENTS_URL__;
const PAGE = '__PAGE__';
const PROVIDER = PAGE + 'bundle-provider.html';
const MODULES = PAGE + 'node_modules/';
const CORE_MAP = { imports: {
  'aiwa-core': MODULES + 'aiwa-core/src/index.js',
  '@noble/curves/': MODULES + '@noble/curves/',
  '@noble/hashes/': MODULES + '@noble/hashes/',
  '@scure/bip39': MODULES + '@scure/bip39/index.js',
  '@scure/bip39/': MODULES + '@scure/bip39/'
} };
const CACHE_KEY = 'aiwa-contract:' + PIN.manifest;
let _ctx = null, _unmount = null, _style = null, _frame = null, _stop = [];

function addMap(text, tag){
  if(document.querySelector('script[data-aiwa-map="' + tag + '"]')) return;
  const m = document.createElement('script');
  m.type = 'importmap'; m.dataset.aiwaMap = tag; m.textContent = text;
  document.head.appendChild(m);
}
function cleanup(){
  _stop.forEach(function(f){ try{ f(); }catch(e){} }); _stop = [];
  try{ if(_unmount) _unmount(); }catch(e){}
  _unmount = null;
  if(_style){ _style.remove(); _style = null; }
  if(_frame){ _frame.remove(); _frame = null; }
}

// What makes the contract immutable: nothing is run that does not hash to the pinned manifest id.
async function verify(pkg){
  const core = await import(MODULES + 'aiwa-core/src/index.js');
  const m = pkg && pkg.manifest;
  if(!m || m.id !== PIN.manifest) throw new Error('these events are not the pinned version');
  if(m.type !== 'bundle.manifest' || m.author !== PIN.author || m.domain !== PIN.domain) throw new Error('wrong publisher or address');
  if(!(await core.verifyEvent(m)).valid) throw new Error('the manifest is not authentic');
  const files = {};
  const listed = (m.payload && m.payload.files) || {};
  for(const path of Object.keys(listed)){
    const e = (pkg.files || []).find(function(x){ return x && x.id === listed[path]; });
    if(!e) throw new Error('a file of the contract is missing');
    if(e.type !== 'bundle.file' || e.author !== PIN.author || e.domain !== PIN.domain || !e.payload || e.payload.path !== path) throw new Error('a file does not belong to this contract');
    if(!(await core.verifyEvent(e)).valid) throw new Error('a file is not authentic');
    files[path] = e.payload.content;
  }
  if(typeof files['index.html'] !== 'string') throw new Error('the contract has no index.html');
  return files['index.html'];
}

function fromCache(){ try{ const t = localStorage.getItem(CACHE_KEY); return t ? JSON.parse(t) : null; }catch(e){ return null; } }
function toCache(pkg){ try{ localStorage.setItem(CACHE_KEY, JSON.stringify(pkg)); }catch(e){} }
async function fromUrl(){
  const r = await fetch(EVENTS_URL, { cache: 'no-store' });
  if(!r.ok) throw new Error('HTTP ' + r.status);
  return r.json();
}
// A window on the Aiwa page of THIS device (which holds the log); it answers with the events and closes.
function fromDevice(){
  return new Promise(function(resolve, reject){
    const origin = new URL(PROVIDER).origin;
    const w = window.open(PROVIDER + '#give=' + PIN.manifest + ';' + encodeURIComponent(location.origin), '_blank');
    if(!w){ reject(new Error('the browser blocked the window')); return; }
    const timer = setTimeout(function(){ done(); reject(new Error('no answer from the Aiwa page')); }, 180000);
    function onMessage(ev){
      if(ev.origin !== origin || !ev.data || ev.data.type !== 'aiwa-bundle' || ev.data.manifest !== PIN.manifest) return;
      done();
      if(ev.data.pkg) resolve(ev.data.pkg); else reject(new Error('this device does not hold that contract'));
    }
    function done(){ clearTimeout(timer); window.removeEventListener('message', onMessage); }
    window.addEventListener('message', onMessage);
  });
}

// Runs the contract's own script here, in the panel (the contract is written for that: see mount(container, host)).
async function inPanel(holder, html){
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const logic = doc.querySelector('script#aiwa-logic') || doc.querySelector('script[type="module"]:not([src])');
  if(!logic) throw new Error('no <script type="module" id="aiwa-logic"> in the contract');
  const map = doc.querySelector('script[type="importmap"]');
  if(map) addMap(map.textContent, 'contract-' + BASE);
  _style = document.createElement('style');
  _style.dataset.aiwaStyle = BASE;
  _style.textContent = Array.from(doc.querySelectorAll('style')).map(function(s){ return s.textContent; }).join('\n');
  document.head.appendChild(_style);
  globalThis.__AIWA_HOST__ = { kind: 'yourmine', ctx: _ctx };
  const url = URL.createObjectURL(new Blob([logic.textContent], { type: 'text/javascript' }));
  let mod;
  try{ mod = await import(url); } finally { URL.revokeObjectURL(url); }
  if(typeof mod.mount !== 'function') throw new Error('the contract does not export mount(container, host)');
  _unmount = await mod.mount(holder, globalThis.__AIWA_HOST__);
}
// The fallback when the browser refuses (an import map that cannot be added late): the verified contract in an isolated iframe.
function inFrame(holder, html){
  const f = document.createElement('iframe');
  f.setAttribute('sandbox', 'allow-scripts');
  f.style.cssText = 'border:0;width:100%;height:100%;min-height:420px';
  f.srcdoc = html;
  holder.appendChild(f);
  _frame = f;
}

function line(container, text, color){
  const d = document.createElement('div');
  d.style.cssText = 'font:11px/1.4 ui-monospace,monospace;opacity:.75;padding:6px 10px;word-break:break-all' + (color ? ';color:' + color : '');
  d.textContent = text;
  container.appendChild(d);
  return d;
}

// Step 3, the one that needs the user: a button, because a window may only be opened from a tap. It returns at
// once (renderPanel must not wait for a tap): the tap goes on with onLoaded.
function askDevice(container, why, onLoaded){
  const box = document.createElement('div');
  box.style.cssText = 'padding:12px 10px';
  const b = document.createElement('button');
  b.className = 'ym-btn ym-btn-accent';
  b.textContent = 'Load the contract from Aiwa (this device)';
  const msg = document.createElement('div');
  msg.style.cssText = 'font-size:11px;margin-top:8px;opacity:.8';
  msg.textContent = why;
  box.appendChild(b); box.appendChild(msg); container.appendChild(box);
  _stop.push(function(){ box.remove(); });
  b.onclick = async function(){
    b.disabled = true; msg.textContent = 'Waiting for the Aiwa window\u2026';
    try{
      const pkg = await fromDevice();
      const html = await verify(pkg);
      toCache(pkg); box.remove();
      onLoaded(html, 'this device');
    }catch(err){ msg.textContent = err.message + ' \u2014 try again.'; b.disabled = false; }
  };
}

window.YM_S['__FILE__'] = {
  name: '__NAME__', icon: '__ICON__', category: 'Aiwa', description: '__DESC__',
  activate(ctx){ _ctx = ctx; },
  deactivate(){ cleanup(); _ctx = null; },
  async renderPanel(container){
    cleanup();
    container.innerHTML = '';
    const tag = 'Aiwa contract ' + PIN.manifest.slice(0, 12) + '\u2026 \u00b7 ';
    const head = line(container, tag + 'checking\u2026');
    const holder = document.createElement('div');
    holder.className = 'aiwa-' + BASE;
    container.appendChild(holder);
    // Runs a contract whose signatures and hashes have just been checked.
    async function start(html, source){
      head.textContent = tag + 'signature and hash checked \u2713 (' + source + ')';
      head.style.color = '';
      try{ await inPanel(holder, html); }
      catch(err){ cleanup(); holder.innerHTML = ''; inFrame(holder, html); }
    }
    try{
      addMap(JSON.stringify(CORE_MAP), 'core');
      let why = 'This sphere holds no copy of the contract: it needs the signed events.';
      const cached = fromCache();
      if(cached){ try{ await start(await verify(cached), 'kept on this device'); return; }catch(e){ /* stale or damaged: ignore it */ } }
      if(EVENTS_URL){
        try{ const pkg = await fromUrl(); const html = await verify(pkg); toCache(pkg); await start(html, 'the public export'); return; }
        catch(e){ why = 'The public export did not work (' + e.message + ').'; }
      }
      head.textContent = tag + 'not loaded yet';
      askDevice(container, why, function(html, source){ start(html, source); });
    }catch(err){
      head.textContent = tag + 'refused: ' + err.message;
      head.style.color = '#d64541';
    }
  },
};
})();
`;

/**
 * The pinned sphere, as { file, source }. author / manifest are 64-hex ids, domain is `contract:<author>:<slug>`;
 * eventsUrl (optional) is where an export of the signed events is published.
 */
export function buildSphere({ author, domain, manifest, slug, title, description, icon, eventsUrl = null, page = PAGE }) {
  if (!HEX.test(author) || !HEX.test(manifest) || !DOMAIN.test(domain) || !SLUG.test(slug)) throw new Error('not a publishable contract identity');
  if (eventsUrl !== null && !/^https:\/\/[^\s'"\\<>]+$/.test(eventsUrl)) throw new Error('the export address must be an https URL');
  const file = `${slug}.sphere.js`;
  const values = {
    __AUTHOR__: author, __DOMAIN__: domain, __MANIFEST__: manifest, __SLUG__: slug, __FILE__: file, __PAGE__: page,
    __EVENTS_URL__: eventsUrl === null ? 'null' : `'${eventsUrl}'`,
    __NAME__: sanitizeMeta(title, 120) || slug,
    __ICON__: sanitizeMeta(icon || '\u{1F537}', 8) || '\u{1F537}',
    __DESC__: sanitizeMeta(description || `${title} — an Aiwa contract, run inside YourMine.`, 120),
  };
  // A function as the replacement: a value holding `$&` or `$1` must be written as it is.
  const source = TEMPLATE.replace(/__[A-Z_]+__/g, (key) => (key in values ? values[key] : key));
  return { file, source };
}
